### ISSUE TITLE
requirements.txt should specify latest version of spacy

### ISSUE THREAD

**Issue by ryanpitts** [ftzeng/broca#2]
Currently broca installs `spacy==0.84`. But when you run `python -m spacy.en.download`, it throws a weird error: `preshed.counter.PreshCounter has the wrong size, try recompiling`

Bumping to `spacy==0.88` seems to fix this problem.

**Comment by frnsys** [comment]
closed in 0d75eb9bf4a25d06e471bda1b48c0b4b0ac20ca8, thanks!
